[tools]
pkl = "latest"
prettier = "latest"

# mise is not detecting pwsh shell or os=windows
hk = {version = "latest", os = ["linux"]}
markdownlint-cli2 = {version = "latest", os = ["linux"]}

[env]
# libgit2 doesn't support git extension "refstorage"
HK_LIBGIT2 = 0
